#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 14 06:54:46 2020

@author: joshua
"""

import pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Process to pSqL") \
    .getOrCreate()


df = spark.read.csv("s3a://living-insight-data/DOB_NOW__Build___Approved_Permits.csv")

df.show()
